apiVersion: v1
kind: Secret
metadata:
  name: atlas-secrets
  namespace: atlasdb
type: Opaque
stringData:
  POSTGRES_USER: "atlas"
  POSTGRES_PASSWORD: "CHANGE_ME"
  JWT_SECRET: "CHANGE_ME_TO_RANDOM_SECRET"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: atlasdb
type: Opaque
stringData:
  POSTGRES_USER: "atlas"
  POSTGRES_PASSWORD: "CHANGE_ME"
  POSTGRES_DB: "atlasdb"
